apiVersion: apps/v1
kind: Deployment
metadata:
  name: react
spec:
  selector:
    matchLabels:
      app: react
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: react
        tier: frontend
        track: stable
    spec:
      containers:
        - name: react
          image: dame94/react-app:latest
