# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
    

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/react-nginx-app
            ${{ secrets.DOCKER_USERNAME }}/node-app
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          file: |
            ./Frontend/Dockerfile
            ./Backend/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/react-nginx-app:${{env.RELEASE_VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/node-app:${{env.RELEASE_VERSION }}
            labels: ${{ steps.meta.outputs.labels }}
