name: Push Docker image to ECR

on:
  release:
    types: [published]
  push:
    branches: [ "main" ]
    

jobs:
  push_to_registry:  
    name: Push Docker image to ECR
    runs-on: ubuntu-18.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: sample
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f Backend/Dockerfile
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
